# Generated by Django 6.0.4 on 2026-05-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destino',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={},
        ),
        migrations.AddField(
            model_name='destino',
            name='best_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='destino',
            name='cover_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='destino',
            name='currency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='destino',
            name='fun_fact',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destino',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='destino',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reserva',
            name='people_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reserva',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='meeting_point',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='tour',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.9, max_digits=3),
        ),
        migrations.AddField(
            model_name='tour',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='time_slots',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='what_includes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='what_not_includes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='destino',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='language',
            field=models.CharField(choices=[('Español', 'Español'), ('English', 'English'), ('Português', 'Português'), ('日本語', '日本語'), ('中文', '中文')], default='Español', max_length=30),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='payment_method',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('paypal', 'PayPal')], default='tarjeta', max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
