# Generated by Django 6.0.4 on 2026-05-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0002_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
    ]
