# Generated by Django 6.0.4 on 2026-05-10 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0003_alter_destino_cover_alter_tour_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destino',
            options={'ordering': ['name'], 'verbose_name': 'Destino', 'verbose_name_plural': 'Destinos'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
        migrations.AlterField(
            model_name='tour',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='destinos.destino'),
        ),
    ]
