# Generated by Django 6.0.4 on 2026-05-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0003_alter_destino_options_alter_tour_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='service_fee',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
