# Generated by Django 6.0.4 on 2026-05-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0004_remove_reserva_coupon_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='people_count',
        ),
    ]
