# Generated by Django 6.0.4 on 2026-05-23 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0005_remove_reserva_people_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creada', 'Reserva creada'), ('confirmada', 'Reserva confirmada'), ('rechazada', 'Reserva rechazada'), ('cancelada', 'Reserva cancelada')], max_length=20)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('realizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_historial', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='destinos.reserva')),
            ],
            options={
                'verbose_name': 'Historial de reserva',
                'verbose_name_plural': 'Historial de reservas',
                'ordering': ['created_at'],
            },
        ),
    ]
